name: esptouch_flutter
description: Flutter plugin for ESP-Touch to configure network for ESP-8266 and ESP-32 devices.
version: 0.1.0
author: Vince Varga <vince.varga@smaho.com>
homepage: https://github.com/smaho-engineering/esptouch_flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.smaho.eng.esptouch
    pluginClass: EsptouchPlugin
