name: esptouch_flutter
description: Flutter plugin for ESP-Touch to configure network for ESP-8266 and ESP-32 devices. Runs on iOS and Android.
version: 0.2.4+1
homepage: https://github.com/smaho-engineering/esptouch_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  meta:

flutter:
  plugin:
    platforms:
      android:
        package: com.smaho.eng.esptouch
        pluginClass: EsptouchPlugin
      ios:
        pluginClass: EsptouchPlugin
